name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: tes
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: rsync over SSH
        run: rsync -r ./foo/ user@remote:bar/
      - name: Push to hub
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "$HF_TOKEN"
          git push https://mrfirdauss:$HF_TOKEN@huggingface.co/spaces/mrfirdauss/endorse-rag master
