name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up SSH
        run: |
          whoami
          pwd
          ls -alh ~
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa huggingface.co >> ~/.ssh/known_hosts
      - name: Push to hub
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "$HF_TOKEN"
          git push https://mrfirdauss:$HF_TOKEN@huggingface.co/spaces/mrfirdauss/endorse-rag master
